# Generated by scripts/formula.ts — do not edit by hand.
class Bryn < Formula
  desc "Terminal code editor"
  homepage "https://github.com/smeltery/bryn"
  version "1.0.0"
  license "PolyForm-Shield-1.0.0"

  on_macos do
    on_arm do
      url "https://github.com/smeltery/bryn/releases/download/v1.0.0/bryn-darwin-arm64.zip"
      sha256 "613bf24df0d69be9185d0742fc3d79cdad43e5ba950e2c9b1b3bc3263f869cc3"
    end
    on_intel do
      url "https://github.com/smeltery/bryn/releases/download/v1.0.0/bryn-darwin-x64.zip"
      sha256 "cc76a81a8bc308c70bfb86e92ee8b4a56127f939f11b90ae86251d02dc1427c2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/smeltery/bryn/releases/download/v1.0.0/bryn-linux-arm64.tar.gz"
      sha256 "de72f067416d1d6f4dd7579618ebc8421b930ca8fd92fdeed3afd30574287a46"
    end
    on_intel do
      url "https://github.com/smeltery/bryn/releases/download/v1.0.0/bryn-linux-x64.tar.gz"
      sha256 "16605825b346983a6b930f83e49204c15302c710764e111b25763f85a40869fc"
    end
  end

  bottle do
    root_url "https://github.com/smeltery/bryn/releases/download/v1.0.0"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "6f570932be899f1f7bf2eafc9283fa0bd0e7dc7f6d03aaa8271b581a653fe104"
    sha256 cellar: :any_skip_relocation, ventura: "394361999b4a4593c04d4708ea8976ac790717d55285b83976d1e966b9e3c886"
    sha256 cellar: :any_skip_relocation, arm64_linux: "de9289c29265cb5b23c54704bf1a8a53e3712782d5849e4f04d637c267a5e351"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "763170019dc490bafdadd00eeb396834846a6aeb15685a3466934022365b7a86"
  end

  def install
    bin.install "bryn"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bryn --version")
  end
end
